### ISSUE TITLE
The path to a new system programming language!

### ISSUE THREAD

**Issue by daokoder** [daokoder/dao#263]
Just some ideas, still very preliminary :)

https://gist.github.com/daokoder/1621c0c106a30f0ee8af

**Comment by dumblob** [comment]
One more thing to DaoJIT and it's incompatibility with the newer versions of LLVM (in which MCJIT was removed). It seems LLVM got not just one, but several new JIT APIs and one - ORC (On-Request Compilation) - of them allows similar use as MCJIT - see https://www.phoronix.com/scan.php?page=news_item&px=LLVM-ORC-JIT-API-Lands (I didn't notice earlier, sorry).

Btw to the topic: there is a system language with Rebol-like (i.e. Lisp-like but without parenthesis) syntax & semantics called [Red/System](https://www.red-lang.org/search/label/red%2Fsystem ) with very active community and more than 8 years of history which achieves similar goals as you @daokoder have described in your last comment:

> I just want to bring the features of a high level language such as Dao to a system programming language, and such system programming language has to be **small** and **clean** with **minimum** dependency.

So maybe there is not such a big urge to have another system language and there is slightly more time for Dao itself :wink:.

**Comment by daokoder** [comment]
> So maybe there is not such a big urge to have another system language and there is slightly more time for Dao itself.

No urge at all. If you haven't brought it up, I almost forgot I haven't closed this issue. Now I will close it for good.
