### ISSUE TITLE
Creating error object from custom type?

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#341]
One may want to create error objects without raising them; namely, a function may expect an `Error` as parameter while you may appear to not have a freshly caught exception to pass in.
```ruby
(dao) const E = Error::define('Error::E')
= none
(dao) e = E()
[[ERROR]] in file "interactive codes":
  At line 0 : Invalid function definition --- " __main__() ";
  At line 1 : Invalid virtual machine instruction --- " CALL:0,0,1 ";
In code snippet:
      0 :  GETCG       :     0 ,    24 ,     0 ;     1;   E
>>    1 :  CALL        :     0 ,     0 ,     1 ;     1;   E()
      2 :  SETVG       :     1 ,     0 ,     2 ;     1;   e = E()
  At line 1 : Types not matching --- " E() ";
```
I can only think about `err = std.try { std.error(e, '') }`, which is too clumsy to be seen as a standard way of achieving this. Meanwhile, this problem does not exist for error *classes*:
```ruby
class E: Error {
    routine E(): Error(''){}
}

e = E()
```
There should better be a way to do this with types as well without extra tricks.

**Comment by daokoder** [comment]
Constructors for error types created by `Error::define()` were not supported for convenience. Now I added support for constructors in such types, in order to fill the gap between this kind of error types and the user derived error types.

**Comment by Night-walker** [comment]
OK, resolved.
