### ISSUE TITLE
Minor leftover

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#350]
`hashing = 0` param in `.associate()` should be replaced with `bool` or, even better, `enum`.

**Comment by Night-walker** [comment]
Also, `min()/max()` should return `none` instead of `(none, -1)`, which is redundant.

**Comment by daokoder** [comment]
> hashing = 0 param in .associate() should be replaced with bool or, even better, enum.

`hashing` is not a boolean parameter, it is actually the hashing seed (0 for no hashing, 1 for default hashing, and else for hashing with customized seed). It should be changed to use enum like `reset()`, where it has `hashing: enum<none,auto,random>`.

> Also, min()/max() should return none instead of (none, -1), which is redundant.

Right.

**Comment by daokoder** [comment]
Actually, the `hashing` parameter should be kept as it is (there are other methods using the same parameter), and the hashing parameter for `reset()` may need rework.

**Comment by daokoder** [comment]
In the end, I think the best option is to use `enum<none,auto,random> | int`, with integer parameter for having the same meaning as now (0: non hashing; 1: default hash seed; 2: random hash seed; >=3: customized hash seed). `int` can be removed, if we do not allow customized hash seed, but it seems harmless if we keep this option.

**Comment by daokoder** [comment]
Done.

**Comment by Night-walker** [comment]
OK, only `min()/max()` left.

**Comment by daokoder** [comment]
Right, now done.
