### ISSUE TITLE
os::PipeStream interface issue

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#351]
`PipeStream::close() => int` is not compatible with `Stream::close()`. I have no idea how it is supposed to work or whether it works at all.

**Comment by Night-walker** [comment]
I think it's better to rename it to `pclose()`, removing the original `os.pclose()`.

**Comment by daokoder** [comment]
> PipeStream::close() => int is not compatible with Stream::close(). I have no idea how it is supposed to work or whether it works at all.

Right, `PipeStream::close() => int` should be changed to `PipeStream::close()`.

> I think it's better to rename it to pclose(), removing the original os.pclose().

Yes, I had considered to remove `os.pclose()`. Actually I also had been wondering if `PipeStream` should be merged with the process pipe you have implemented. Do you see if it is appropriate?

**Comment by Night-walker** [comment]
> Actually I also had been wondering if PipeStream should be merged with the process pipe you have implemented. Do you see if it is appropriate?

I suppose it is usually simpler to just use `popen()` which is sufficient most of the time, without delving into the process management details.

**Comment by daokoder** [comment]
> I suppose it is usually simpler to just use popen() which is sufficient most of the time, without delving into the process management details.

Right, it is probably too heavy to use process management for usual tasks. But the name `PipeStream` still feels a bit strange, it was a temporary name I made up to avoid name clashing with the process pipe. We need a better name for this.

**Comment by Night-walker** [comment]
`ProcessStream`? `ShellStream`?

**Comment by dumblob** [comment]
`ShStream`? `ShellStream`?

**Comment by daokoder** [comment]
Maybe just `Shell`?

**Comment by dumblob** [comment]
I considered `Shell` as well, but I'm afraid of confusion with `system()`.

**Comment by Night-walker** [comment]
`Shell` is too vague and misguiding. Since it's a `io::Stream` subclass with minimal differences from its parent, `*Stream` would be better, I suppose.

**Comment by Night-walker** [comment]
Fixed with `PipeStream::pclose()`.
