### ISSUE TITLE
Public constructors in modules

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#352]
Once again, I'm facing the very same design pattern -- there are classes which are not supposed to be directly instantiated by the user. A simplest example is `os::Path` I rolled out recently.

It is not sufficient to just comment it like "don't you dare use this constructor!!!"; and it is quite ridiculous when a monumental module architecture may crumble miserably if you mistakenly use what you're not supposed to.

I think there is need for ability to define constructors which appear public in the scope of a module, but become private/protected from outside it. In the simplest case, any `protected` constructor, for instance, may be deemed `public` within the current source file or files which are included by this file.

While this does not strictly seal off such constructor from the user, the chance of misuse is lower because sub-classing or mixing a class is not an action to be performed spontaneously.

**Comment by dumblob** [comment]
I'm not convinced such global rule would be the proper solution as it forces a semantical connection of some characteristic of a particular class with project file structure. Such constraint should be checked inside of the constructor (e.g. using some `meta` information) and raise error exception. Of course it would be nice to check it in compile-time, but in my opinion this is no so common case being worth enhancing the current syntax and adding complexity due to the connection between content of a file and constructor restrictions.

Actually, I'd say it's a more general problem - similar constraints might be needed for other methods as well...

**Comment by Night-walker** [comment]
The syntax would not change, actually, and certain language features -- like aspect classes -- are already  applied depending on the file structure, so it won't be anything new.

> Such constraint should be checked inside of the constructor (e.g. using some meta information) and raise error exception.

I would like to avoid such pythonish hack, e.g. `if __name__ == "__main__":` we call `main` function, else the file is loaded as a module. 

Certain interface (a constructor in our case) simply should not be exposed to "unauthorized" use. It will be a very frequent case if more modules get written in Dao, so a simple and effective (compile-time) way of enforcing restrictions is preferable.

**Comment by dumblob** [comment]
Maybe I misunderstood you - which of the following shouldn't be allowed in other files:

~~~~ruby
class A {
  routine A(x: int) {}
}

y = A(5)
y.A(55)
z = A.A(6)
z.A(66)
~~~~

I don't see any difference between them, so if you want to disable instantiation, simply don't export the class.

**Comment by daokoder** [comment]
> files which are included by this file.

This would be very confusing.

**Comment by Night-walker** [comment]
> so if you want to disable instantiation, simply don't export the class

And how to use it then?

**Comment by daokoder** [comment]
> I'm not convinced such global rule would be the proper solution as it forces a semantical connection of some characteristic of a particular class with project file structure. 

I agree.

> Such constraint should be checked inside of the constructor (e.g. using some meta information) and raise error exception.

I also considered this. But it maybe too inconvenient.

**Comment by daokoder** [comment]
> And how to use it then?

I just come up with one solution:
~~~ruby
namespace NameSpace{ PublicClass }

class PrivateClass
{
    routine PrivateClass( x: int ){  # public constructor;
    }   
    routine PrivateClass( x: PrivateClass ){  # private constructor;
    }   
}

interface PublicInterface
{
    routine PublicInterface( x: int );
}

const PublicClass: PublicInterface = PrivateClass
~~~

Note: it is not working now, but I intend to fix it.

**Comment by Night-walker** [comment]
Nice workaround, but too cumbersome. Moreover, if I use exported `routine fun() => PublicClass` within the module, I will have to manually convert it too `PrivateClass` to have access to private interface, which  isn't nice already. And a lot of boilerplate code.

**Comment by daokoder** [comment]
> Moreover, if I use exported routine fun() => PublicClass within the module, I will have to manually convert it too PrivateClass to have access to private interface, which isn't nice already.

Right, that would be inconvenient. But I am against to add new feature or the kind for solving this issue. Mainly because adding new things to solve new problems more nicely will surely lead to bloated design and implementation.

Now another simple workaround:
~~~
namespace NS { MyClass }

class DummyClass
{
}
class MyClass
{
    routine MyClass( dummy: DummyClass, other_parameters ){  # private constructor;
    }
}
~~~
Since `DummyClass` is private and not exported, the constructors with this parameter cannot be used by users! Not very elegant, but I suppose it is simple and convenient enough:)

**Comment by Night-walker** [comment]
> Since DummyClass is private and not exported, the constructors with this parameter cannot be used by users! Not very elegant, but I suppose it is simple and convenient enough:)

I had exactly the same idea :) It is acceptable if it won't cause any unexpected side effects.

**Comment by dumblob** [comment]
>but I suppose it is simple and convenient enough:)

I think it is ;)

**Comment by dumblob** [comment]
We should also add this hint to documentation or some FAQ section.

**Comment by Night-walker** [comment]
The only problem with 'private tokens' as constructor arguments is that if effectively seals the class, forbidding any kind of inheritance. That's why I won't use this for `os::Path`, though such approach is feasible in some other cases.

**Comment by daokoder** [comment]
> The only problem with 'private tokens' as constructor arguments is that if effectively seals the class, forbidding any kind of inheritance. 

I don't see why this is the case. You may just need to define explicit constructors in derived classes with explicit calling to a parent constructor (one without 'private tokens').

**Comment by Night-walker** [comment]
> You may just need to define explicit constructors in derived classes with explicit calling to a parent constructor (one without 'private tokens').

Well, if *there is* a 'public' constructor, then yes. It should then be somehow different from the private one  to make any sense. And, since the vital internals are not to be exposed via such constructor, one might not be able to extend the class in a useful way.

This will probably not be a serious problem, however. But one should nevertheless be aware of this when using 'private tokens'.

**Comment by dumblob** [comment]
>But one should nevertheless be aware of this when using 'private tokens'.

It'll be in documentation, which should be enough, right?

**Comment by Night-walker** [comment]
I think this one can be closed.
