### ISSUE TITLE
for loop, modifying control variables, and invar

### ISSUE THREAD

**Issue by dumblob** [daokoder/dao#364]
According to https://github.com/daokoder/dao/issues/173 and current documentation, this should work:
~~~~
0$ dao -e 'a = 2; b = 2; c = 50; for (invar i = a : b : c) io.writeln(i, a, b, c)'
[[ERROR]] in file "command line codes":
  At line 0 : Invalid function definition --- " __main__() ";
  At line 1 : Invalid virtual machine instruction --- " ADD:6,3,6 ";
In code snippet:
      7 :  GOTO        :     0 ,     9 ,     0 ;     1;   i = a : b : c
>>    8 :  ADD         :     6 ,     3 ,     6 ;     1;   i = a : b : c
      9 :  LE          :     6 ,     5 ,     7 ;     1;   i = a : b : c
  At line 1 : Constant or invariable cannot be modified --- " i = a : b : c ";
~~~~
Another question arises from the modification of control variables. We already discussed this shortly somewhere, but it was before the introduction of `invar`. So again, should we allow their modification if we have the full-featured C-like for loop `for (i=a; i<=c; i+=b)`? Currently the loop evaluates the variables in each round which has only a negligible performance advantage over the C-like for loop, so the arithmetic progression for loop looks more like a syntactic sugar. Is this how you meant it's meant to be? Or should we rather consider `a` `b` `c` as `invar` and issue a compile-time warning?
~~~~ruby
stop = 20
a = 2
b = 2
c = 50
for (i = a : b : c) {
  io.writeln(i, a *= a, ++b, ++c)

  if (--stop <= 0) break
}
~~~~

**Comment by daokoder** [comment]
This appears to be a regression error.

> so the arithmetic progression for loop looks more like a syntactic sugar. Is this how you meant it's meant to be? 

No, it is not a syntactic sugar. The expressions in the `for` brackets are supposed to be evaluated at the start to define the loop pattern.

> Or should we rather consider a b c as invar and issue a compile-time warning?

Not necessarily. The values of `a b c` should have no effects on the loop once it is started.

**Comment by Night-walker** [comment]
> The expressions in the for brackets are supposed to be evaluated at the start to define the loop pattern.

Right, that's the best behavior in this case.

**Comment by daokoder** [comment]
Fixed.

**Comment by dumblob** [comment]
Right, now the variables are caught at the beginning of the for loop and can be modified afterwards without intervening with the loop itself.
