### ISSUE TITLE
Enhancement: One-time decorators that execute statically

### ISSUE THREAD

**Issue by ShadauxCat** [daokoder/dao#371]
Currently, decorators in Dao execute when the function is called and modify the result. However, one of the most useful aspects of decorators in python for me has been the ability to have it perform an action on the function itself rather than altering the way the function behaves. This is particularly useful for registering functions as event handlers.

An example in python might be something like this:

```
eventHandlers = {}

def RegisterEventHandler( eventType ):
    def wrap( func ):
        eventHandlers[eventType] = func
        return func
    return wrap

@RegisterEventHandler( EventType.SomeEvent )
def HandleSomeEvent():
      # ... do stuff ...
```

All this decorator does is add the function in question to a list of event handlers and then return that function completely unmodified, so the decorator function itself never gets called again. This is great because the decorator puts the registration of the function as an event handler in the same location as the definition of the function, making it both immediately obvious what the function does and how it interacts with the system, and also very clean and easy to read. But something like this isn't possible in Dao right now, because HandleSomeEvent() won't be registered as an event handler until after it's called, and then it will get re-registered every time it's called.

It would be really awesome if there were a feature in Dao that could mimic this behavior of Python. Possibly using a different decorator syntax - maybe @@Decorator for static decorators, or !Decorator, to designate that this should be executed on the function as soon as the function's fully defined rather than being delayed until the function is called. (And naturally, a decorator like this would take a first parameter of the function without any bound arguments, as opposed to the func(args) parameter used by existing decorators.)

**Comment by Night-walker** [comment]
This is a useful ability, no doubts. Beside event handlers, there are things like RPC or FFI which could benefit greatly from this feature. In general, it is somewhat similar to what attributes/annotations are for in Java, C#, Go and Rust. However, it demands to rethink not just the meaning of decorator in Dao, but also the way code gets executed.

Such static decorators would need to be executed at some point of time and in specific order. Not only they may introduce side effects -- this is their exact purpose, so it is quite important to form accurate understanding of what can possibly happen when things are set in motion. 

At present, no run-time code is allowed within classes (they are *constants*, as far as I know), so the picture of starting program is easy to comprehend: loaded binary modules perform their initialization (which normally doesn't affect the way code is run), then `var`s and `invar`s are initialized in the order they appear in the code. And then `main()` is called (when it's present), or the control flow just proceeds through the script code.

With static decorators, the whole new layer of initialization-time code is introduced. They may be just about anywhere, lurking in any class you import into your code. It may then become quite difficult to reason how the code is run, leaving the programmer in dangerous impression that "here happens magic".

By the way, there are aspect classes to take into account. They may complicate things further if static decorators are allowed to be used with them. And that's not counting wrapped (C-written) classes: of course, they don't have even ordinary decorators by now, but there is actually no reason why they can't have them. Then, imagine static decorators coupled with on-demand wrapping of such classes (if I recall correctly): one could awaken ~~ancient evil~~ hidden code by mere mention of class name.

A less "invasive" approach would be to use (static) decorators to assign metadata to certain functions.  Parametric labels, just like with the attributes I mentioned before. Then this metadata can be extracted via reflection capabilities and interpreted accordingly. This can be used to achieve the same end result, but the code execution model would be simpler -- labels themselves are constant and thus get evaluated at compile time with no side effects. Also, such approach can be used (and is often used) to introduce new compile-time features without the need for syntax changes.

Still, more consideration is required. One way or another, it is a significant change to the language which should be adopted only if its value outweighs the added complexity.

**Comment by dumblob** [comment]
Hm, to me this seems like a very specific use-case (but apparently common in the Python community). I'm afraid, that the approach you demonstrated has undefined/inconvenient order of assignment to the global `eventHandlers[]` list or in general, undefined/inconvenient order of calling the `wrap()` function. I'd expect the order being dependent on the order of parsing of the files, which is very inconvenient (for programs larger than few hundreds of lines).

I doubt it's necessary to introduce something like this - it'd introduce a lot of confusion for only a small benefit.

**Comment by ShadauxCat** [comment]
Yeah, I know this one's a big change. But it is a very common use for decorators, and I have to admit that I was a little disappointed when I started playing with Dao and found that I couldn't do with decorators what I wanted to. This is actually my primary use-case for decorators, so not being able to do this means decorators have very minimal usefulness to me. (I realize that's a very personal and subjective concern, but it is the reason I brought it up.)

In terms of initialization, I would expect global variables (and invariables) to be initialized first, then static decorators to be called in the order they appear (C++ works the same way - it has a static initialization pass where trivial types are initialized first, then a dynamic initialization pass where non-trivial types are initialized and functions in the global scope are called; likewise, Python initializes everything in the order it appears, so the same issue of potential side-effects exists there without any real issues from it). Then I would expect a nested function to be initialized like a static local variable in C/C++ - created the first time the function is called. (Though, if Dao creates this as the concept of 'acting on a function' rather than 'replacing a function' and continues with its current path of 'function as the first argument, additional arguments follow', the 'wrap' function would be unnecessary anyway.)

If you guys don't think it's a useful thing to add, I'm not going to argue. But at the least, I figured it couldn't hurt to bring it up for discussion, because I think there are a lot of people who would get good use out of it.

**Comment by ShadauxCat** [comment]
I achieved exactly what I want through a syntax macro:

```
syntax {
	'!' $ID1 [ '(' $BL1 ')' ]
	'routine' $ID2 '(' [ $BL2 ] ')'
	'{'
		[ $BL3 ]
	'}'
} as {
	'routine' $ID2 '(' [ $BL2 ] ')'
	'{'
		[ $BL3 ]
	'}'
	'{'
		'func' '=' $ID1 ';'
		'arg' '=' $ID2 ';'
		'func' '(' 'arg' [ ',' '(' $BL1 ')' ] ')' ';'
	'}'
}
```

Not entirely certain why I had to bind `$ID1` and `$ID2` to variables `func` and `arg`. It didn't do anything if I just tried to do ` $ID1 '(' $ID2 ')' ';'`. But this works, and does exactly what I want it to. (Have I mentioned I love the syntax macros? Those things are just friggin' awesome.)

Just replaces:

```
!StaticDecorator
routine Myfunc()
{
    # ...
}
```

With:

```
routine MyFunc()
{
   # ...
}
StaticDecorator(MyFunc);
```

Which is exactly what I want.

Example code using it:

```
var eventHandlers = { -> }

enum EventType
{
	Default,
	TestEvent,
	OtherEvent
}

routine RegisterEventHandler(func, eventType)
{
	eventHandlers[eventType] = func;
}

routine RegisterDefaultEventHandler(func)
{
	eventHandlers[EventType.Default] = func
}

!RegisterDefaultEventHandler
routine HandleDefaultEvent()
{
	io.writeln("Handling default event");
}

!RegisterEventHandler(EventType.TestEvent)
routine HandleTestEvent()
{
	io.writeln("Handling TestEvent")
}

!RegisterEventHandler(EventType.OtherEvent)
routine HandleOtherEvent(str)
{
	io.writeln("Handling OtherEvent", str)
}

eventHandlers[EventType.Default]()
eventHandlers[EventType.TestEvent]()
eventHandlers[EventType.OtherEvent]("with an argument")
```

Now if that segfault when using syntax macros with a language name is fixed, I'll be perfectly happy.

**Comment by Night-walker** [comment]
> so the same issue of potential side-effects exists there without any real issues from it

He-he, you just didn't encounter the issues. In C++, static variable initialization is actually a complicated process, particularly in concurrent environment. The order in which initialization code is run may easily differ from the order in which variables appear in code, under [certain circumstances](https://github.com/daokoder/dao/issues/46#issuecomment-21785192).

In Dao, we would face the very same problems. What if an error is raised during such initialization code? Most likely you won't be able to handle it in any possible way. What if it causes a deadlock? It would be out of control.

> Then I would expect a nested function to be initialized like a static local variable in C/C++ - created the first time the function is called.

As I already pointed out, it's a delusion, about C++. Some things only seem simple, until you discover their real nature hidden beneath the envelope. Fortunately, Dao static variables are required to be initialized to constants, which saves us from accidental dragon outbreaks. This is a deliberate limitation, and a reasonable trade-off.

> If you guys don't think it's a useful thing to add, I'm not going to argue. But at the least, I figured it couldn't hurt to bring it up for discussion, because I think there are a lot of people who would get good use out of it.

It's useful, but that's not enough to embrace it with awe and delight. I, for instance, would opt for attribute-like semantics rather then decorator-like. Still, I would like to find more use-cases for it before jumping into conclusions about its usefulness.

**Comment by ShadauxCat** [comment]
Oh don't get me wrong, I've encountered lots of issues with it in C++. Just not in Python. ;) But the C++ issues are almost entirely related to global variables *in different modules* having an undefined initialization order. And concurrency shouldn't be an issue, as if you're starting multiple threads before you hit main(), you're doing something wrong and just asking for trouble...

Global variables within one module have a strictly defined initialization order in C++ - they are initialized in the order they appear. In Dao, since modules are only loaded with a "load" call, that order can be controlled in ways it can't be in C++ (same with python). If I load module A and it needs module B initialized before it, it just loads module B. (Of course if there are circular dependencies there, then that's a problem, but that's a problem with the architecture of the modules in question, and not one Dao should even try to fix.)

Static local variables in C/C++ ARE very strictly defined, however, to be initialized at the moment the function is called. If they behave any differently than that, you have a buggy compiler. (This is static *local* variables mind you - variables defined static within the scope of a function. Non-local static variables are a can of worms.)

Regardless, we're just arguing semantics here. The syntax macros gave me a solution (as I said above) so I'm not all that concerned about it. I think it'd be useful for other people to have it, but I at least have what I need to accomplish what I want to accomplish (and am willing to handle making sure that I do it safely - C++ is my primary language so I, at least, am used to that) so I'm not going to press the point. The syntax macros are probably my favorite part of Dao for exactly this reason.

**Comment by dumblob** [comment]
Nice macro! I'd vote for adding it to our documentation as an example (presumably very important for Python guys :wink:).

**Comment by ShadauxCat** [comment]
Sure. Glad you like it! Let me provide its companion for classes as well, then:

```
syntax {
	'!' $ID1 [ '(' $BL1 ')' ]
	'class' $ID2 [ '(' $BL2 ')' ] [ ':' $BL3 ]
	'{'
		[ $BL4 ]
	'}'
} as {
	'class' $ID2 [ '(' $BL2 ')' ] [ ':' $BL3 ]
	'{'
		[ $BL4 ]
	'}'
	'{'
		'func' '=' $ID1 ';'
		'arg' '=' $ID2 ';'
		'func' '(' 'arg' [ ',' '(' $BL1 ')' ] ')' ';'
	'}'
}
```

I also tested changing that to be `[ DecoratorName ]` instead of `!DecoratorName` and that worked just fine as well.

Caveat here, though, is that this is my second day playing with Dao, so I'm not willing to call these 'tested' by any stretch of the imagination. I don't know if these handle all the ways that routines and classes can be defined or not. But they work for the cases I've tried so far. (Which aren't very many)

Quick question: Is there any form of auto-load module for dao? Seems like making these sort of syntax changes would be something I'd like to apply at the workspace level. Having something like .daorc that automatically gets loaded and executed so every file in my workspace gets my syntax macros without having to load them explicitly would be nice for workflow reasons. Does anything like that exist? (If not, not a big enough concern to open an issue for it, just a curiosity. Typing 'load syntaxmodule' in each file isn't so bad.)

**Comment by Night-walker** [comment]
> Static local variables in C/C++ ARE very strictly defined, however, to be initialized at the moment the function is called. If they behave any differently than that, you have a buggy compiler. (This is static local variables mind you - variables defined static within the scope of a function. Non-local static variables are a can of worms.)

You didn't read C++ specification draft on this. What I described in the comment I gave the link to is how C++ is required to handle static variable initialization, not a bug or compiler's whim. Static variables may end up initialized in undetermined order, and rvalue code bound to them may actually run multiple times.

**Comment by ShadauxCat** [comment]
If you call the function on multiple threads at the same time, sure, you can end up with the static getting instantiated more than once, that's a race condition. But barring race conditions, the C++ standard DOES say that static local variables are initialized at the moment the function is called, not before and certainly not after. Again, this is specific to static locals. Static globals follow a different rule and are a huge mess.

**Comment by Night-walker** [comment]
> If you call the function on multiple threads at the same time, sure, you can end up with the static getting instantiated more than once, that's a race condition. But barring race conditions, the C++ standard DOES say that static local variables are initialized at the moment the function is called, not before and certainly not after. Again, this is specific to static locals. Static globals follow a different rule and are a huge mess.

No, no, no. You still don't understand. Just read that comment of mine. Read the specification, if you don't believe me. It has nothing to do with race conditions.

**Comment by Night-walker** [comment]
> Quick question: Is there any form of auto-load module for dao?

Nope, there isn't. Personally, I'm against loading anything implicitly.

**Comment by dumblob** [comment]
>Quick question: Is there any form of auto-load module for dao?

No. In general, we're trying hard to avoid making anything implicit.

**Comment by ShadauxCat** [comment]
Referencing Scott Meyers' *Effective C++*, he says:

> ... move each non-local static object into its own function, where it is declared static. ... In other words, non-local static objects are replaced with *local* static objects. ... This approach is founded on C++'s guarantee that local static objects are initialized when the object's definition is first encountered during a call to that function.

I generally trust Scott Meyers when he talks about the standard, but just to be sure, I looked up what the standard says, and it does say:

> An implementation is permitted to perform early initialization of other local objects with static storage duration under the same conditions that an implementation is permitted to statically initialize an object with static storage duration in namespace scope (3.6.2).

So I have to concede that the standard does allow these things to be constructed early before the function is called, and in undefined order. **However, I also have to contend that this is an allowance that no modern compiler I know of actually makes use of.** Every compiler I am aware of defers initialization until the function is called, which generally makes the assumption of initialization order of static local variables a safe assumption. (Even if Scott Meyers is wrong about it being guaranteed by the standard, if it's guaranteed by enough compilers for him to use the word 'guarantee,' I will trust him on that. He's a very smart guy when it comes to C++.)

**Comment by Night-walker** [comment]
About C++ static variables local to a function. An excerpt from C++ specification draft published by C++ Standards Committee I consulted previously, albeit I won't give you the exact chapter and page. 

First, their initialization in concurrent environment is done in implicit critical section. Then, if it fails, it will be undertaken *again* next time the function is called. Finally, behavior of recursive initialization is undefined.

**Comment by dumblob** [comment]
I think this discussion pretty much demonstrates that complicated things are a no-go for safe language with built-in concurrency, which Dao is.

**Comment by ShadauxCat** [comment]
> First, their initialization in concurrent environment is done in implicit critical section. Then, if it fails, it will be undertaken again next time the function is called. Finally, behavior of recursive initialization is undefined.

This is all extremely pedantic and really completely unrelated to this issue, but none of that really impacts the initialization order of static local functions. The first point doesn't change initialization order at all, the second only deals with failure cases (which, if you're throwing exceptions in a constructor, that's going to result in really bad things happening regardless of whether or not the object is static) and doesn't change the initialization order. The initialization may *fail*, but it's still *performed* (or at least attempted) in a well-defined and predictable order. And the last bit about recursive initialization, I don't know how that even COULD be defined. Static or otherwise, I would expect *any* attempt at recursive initialization to result in infinite recursion until it hits the maximum stack depth and crashes.

REGARDLESS, this is all irrelevant, because I found (and already posted) a solution that works great for me within the existing Dao framework with no changes to Dao required. So I'm closing this issue.

**Comment by Night-walker** [comment]
By the way, @ShadauxCat, the macro won't work for class methods. If you need that, you'll have to devise a different macro which would put the calls outside of the class. Just a remark.

**Comment by ShadauxCat** [comment]
Fair point. I'll work on that and see what I can come up with.
