### ISSUE TITLE
Nested defer(){} not functioning correctly

### ISSUE THREAD

**Issue by ShadauxCat** [daokoder/dao#382]
```
routine GetNone()
{
    defer(Error)
    {
        defer(Error)
        {
            return none;
        }
        std.error("None");
    }
    std.error("None");
}
io.writeln(GetNone());
```

This should print `none` every time. I've seen very inconsistent results with this. Usually it seems to print a routine identifier (presumably it's printing GetNone itself rather than the return value) instead of the expected `none`. I have seen it print `none` a couple of times but it's not consistent.

Caveat here, I was running through the demo on the website, and I don't know how up to date that is or whether it might have some unusual behavior that wouldn't be seen normally.

**Comment by Night-walker** [comment]
Tried it in the interactive mode. Prints `none` every time as expected. The demo may easily run on an outdated Dao version.

**Comment by ShadauxCat** [comment]
Good enough for me. Closing.
