### ISSUE TITLE
For loops lacking 'continue' option

### ISSUE THREAD

**Issue by ShadauxCat** [daokoder/dao#385]
This seems like a ubiquitous enough language feature that I would hope its usefulness is self-evident. But just in case, consider the following:

```
for(value in someList)
{
   if(!value.someCondition())
   {
        value.doSomeInspection();
        if(!value.otherCondition())
        {
            PrepareSomeStuffOn(value);
            if(ShouldExecuteLoopOn(value))
            {
                # ... loop ...
            }
        }
    }
}
```

Compare this to:

```
for(value in someList)
{
    if(value.someCondition) continue;

    value.doSomeInspection();
    if(value.otherCondition) continue;

    PrepareSomeStuffOn(value);
    if(!ShouldExecuteLoopOn(value)) continue;

    # ... loop ...
}
```

In large codebases with complicated for loops involving many potential early out conditions, nesting if blocks can become very difficult to read and maintain. In some loops these blocks could get 10 levels deep with early out conditions.

(The `break` statement does seem to exist, so it's possible this does exist by a different name and isn't documented)

**Comment by ShadauxCat** [comment]
Current specific case I need this, writing some code to parse a string and need to take actions based on the character I find. Without `continue`, each character has to be written one level deeper inside an `else` block. This is getting really deeply nested really fast and running off the edge of my screen, which makes it really hard to read.

**Comment by Night-walker** [comment]
`skip` :)

**Comment by ShadauxCat** [comment]
Many thanks.
