### ISSUE TITLE
Uninitialized variables: evil returns

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#400]
Look at this, doesn't it feel fundamentally wrong?
```ruby
(dao) class A {
..... var f: io::Stream
..... }
= none
(dao) a = A()
= A[024CECF8]
(dao) a.f
= none
(dao) x: A
= none
(dao) x
= none
(dao) io.writeln(x)
# CRASH
```
Unitialized variables are `none` whereas their type has no indication of it. This throws us back to the ~~Medieval age~~ same problem with magic 'no-value' which can slip in everywhere and ruin seemingly correct code. And it's not even the "good none", it's some kind of bad, evil `none` which evidently may lead to crashes.

That's a serious flaw, and it should be fixed. And the only plain and simple solution I see is forbidding the use of uninitialized data once and for all. Everywhere. So that it can never break free and cause havoc during code execution.

First, all standalone variables must be initialized at the place of their definition *unless* we can track their further use and ascertain that it is 100% correct in all possible cases, always. Apparently, it doesn't work that way at present.

Second, constructors must initialize all class fields. If that is somehow problematic to ensure (and it seems for me that it may be so), then the very idea of constructor must change. I, for one, can propose Rust's approach: no constructors; create objects manually (via static methods) specifying all their content immediately without missing a single field. As with `Class.{...}` packing in Dao.

That's it.

**Comment by dumblob** [comment]
I actually can't fully agree on this. I've seen enough places where the *implicit value* allowed great code structuring and was very inevitable/useful also for delayed or on-demand/lazy fetching etc. I think, that the crash you've shown can be prevented in all cases (e.g. by adding another tag to variables - I saw already some tag there, but I couldn't prove its use in the whole parser) and an exception should be raised at the place of its use.

If one needs absolute assurance, than the `Class.{...}` packing should be used at all places and to be completely safe. In other words, it's more about the coding policy than about the language.

And yes, this is more or less another Dao dualism (*packing* versus *implicit value*) ;)

**Comment by Night-walker** [comment]
> I actually can't fully agree on this. I've seen enough places where the implicit value allowed great code structuring and was very inevitable/useful also for delayed or on-demand/lazy fetching etc. I think, that the crash you've shown can be prevented in all cases (e.g. by adding another tag to variables - I saw already some tag there, but I couldn't prove its use in the whole parser) and an exception should be raised at the place of its use.

Explicit initial value is *always* better then default value. It's just that it may sometimes be helpful to "delay" initialization of variable until the value is known or gets used (lazy init). That's what Rust allows, for instance -- and it's perfectly safe. But the use of *uninitialized* variables can only lead to errors, and hence no modern language allows it.

Lazy initialization (I think that's what you meant) is fine as long as language handles it correctly, which is not the case for current Dao. If, for some reasons, it is problematic to ensure initialization before use, mandatory initialization at the place of declaration is always a viable solution.

> If one needs absolute assurance, than the Class.{...} packing should be used at all places and to be completely safe. In other words, it's more about the coding policy than about the language.

it's not about the coding policy. When you use unitialized variables of fields in Dao, it shatters all the typing system to pieces, make the code panic or even crashes the VM. It's not C++ to allow writing any nonsense which then works in unintuitive or undefined way. Variables and invariables *must* be initialized prior to their use, somehow -- otherwise the guarantees given by the typing system are all for naught.

**Comment by Night-walker** [comment]
Now, after the latest commit, it's impossible to declare *reference-based* values without initialization. I'd suggest to extend this rule on all variable types. Relying on default values makes the code confusing and error-prone; besides, initializing a variable with e.g. `0` or `""` should bear no overhead anyway.

I also urge to consider changing the very idea of constructors. Yes, the check for uninitialized variables works -- but it works at runtime. Not very nice, performance suffers too. It's OK as a temporary workaround, but I think we should adopt a better alternative in the long run.

**Comment by daokoder** [comment]
> Now, after the latest commit, it's impossible to declare reference-based values without initialization.

Right. I hope this does not create much inconvenience.

>  I'd suggest to extend this rule on all variable types. Relying on default values makes the code confusing and error-prone; besides, initializing a variable with e.g. 0 or "" should bear no overhead anyway.

Agree. It will be done.

> Yes, the check for uninitialized variables works -- but it works at runtime. Not very nice, performance suffers too. It's OK as a temporary workaround, but I think we should adopt a better alternative in the long run.

I think the checking can be done at compiling time in principle. It is very simple for object packing (uniform initialization). But for constructors, it will need some static program analysis, it is not difficult, if the members are required to be initialized right inside the constructors. But if the constructors call other method to do the initialization, it may become very tricky in some cases.

It seems to me that, requiring class members to be initialized inside constructor bodies is completely acceptable, because one can always build values with methods, and return and **assign** them to the members inside constructors. In this case, I will consider to add static checking at compiling for class members.

**Comment by Night-walker** [comment]
> I think the checking can be done at compiling time in principle. It is very simple for object packing (uniform initialization). But for constructors, it will need some static program analysis, it is not difficult, if the members are required to be initialized right inside the constructors. But if the constructors call other method to do the initialization, it may become very tricky in some cases.
> 
> It seems to me that, requiring class members to be initialized inside constructor bodies is completely acceptable, because one can always build values with methods, and return and assign them to the members inside constructors. In this case, I will consider to add static checking at compiling for class members.

There always exist a possibility to switch to packing as the only way to create class instances:
```ruby
class A {
private:
    var stream: io::Stream

public:
    static routine new(stream: io::Stream) => A {
        A.{stream} # as we're inside A's method, it should be allowed to address private fields
    }
}
```
As you pointed out, it is simple to ensure correctness here, and it's not very burdening to define and use. That's how Rust handles it, and I find it feasible for Dao as well.

**Comment by dumblob** [comment]
I see your point @Night-walker in the post https://github.com/daokoder/dao/issues/400#issuecomment-109713946 and must agree with everything (yes, I meant lazy initialization).

**Comment by Night-walker** [comment]
Considering static methods instead of constructors, I forgot about inheritance. That would require a special approach, something like this
```ruby
```

**Comment by Night-walker** [comment]
> Well, since it should not have parameters, it can't be overloaded, so we can just pick the first (and only) routine< => ourAspectClass> declared in ourAspectClass (if there is such routine at all), which ought to be the constructor we seek.

Ehmm, no. There may possibly be multiple static methods returning instances of the current class, so deciding which one is supposed to be the constructor may be problematic...

**Comment by daokoder** [comment]
I think it's better to keep constructors. Removing it might require a lot of changes, and affects several features. Instead, I am seriously considering to add the requirement I mentioned previously, so that instance members are required to be initialized *directly* inside the constructors.

**Comment by Night-walker** [comment]
> I am seriously considering to add the requirement I mentioned previously, so that instance members are required to be initialized directly inside the constructors.

OK, that should suffice.

**Comment by daokoder** [comment]
Done.

**Comment by daokoder** [comment]
Done.

**Comment by Night-walker** [comment]
It is still possible to declare uninitialized variables of primitive types, which should better be disallowed as well.

**Comment by daokoder** [comment]
> It is still possible to declare uninitialized variables of primitive types, which should better be disallowed as well.

If you mean class instance variables of primitive types, that's intentional. If that is disallowed, some programs I wrote will be broken. Those variables are actually initialized, to their default values (zeros and empty strings etc.).

**Comment by Night-walker** [comment]
I mean *all* variables of primitive types. From the point of clarity, relying on default values is a bad idea. As for the code which can become broken, that can be fixed with certain amount of `sed` magic, no?

**Comment by daokoder** [comment]
> I mean all variables of primitive types.

I thought that is possible only for instance variables. But it turns out that's not the case, currently this is also allowed for global variables, which is not intentional.

> From the point of clarity, relying on default values is a bad idea.

Well, if clarity must be enforced, all variable must be explicitly initialized. But this might make it a bit annoying in particular cases. For example, for a SQL database table, one might define the corresponding class like:
~~~ruby
class Block
{
    var  block_id    : SQL::INTEGER_PRIMARY_KEY_AUTO_INCREMENT;
    var  block_code  : SQL::VARCHAR8;
    var  zone_id     : SQL::BIGINT;
    var  zone_code   : SQL::VARCHAR32;
    var  relay_id    : SQL::BIGINT;
    var  longitude   : SQL::FLOAT;
    var  latitude    : SQL::FLOAT;
    var  address     : SQL::VARCHAR128;
}
~~~
Here you cannot replace `var name: type` with `var name = value`, because the type names are required for correctly mapping to SQL types. So to explicitly initialize the fields, you have to use `var name: type = value`, then the table might look less clear. Ok, this may be subjective, but when there are many such tables, it really gets a bit ridiculous. Also when all fields are explicitly initialized, you will not have the option to define SQL tables with just some fields having default values.

My opinion is that, primitive types (such as none, bool, int, float, complex and string) in class instance fields should support initialization with default values, since it is pretty obvious what the default values should be (note that I excluded enum, whose default value might not be as obvious). Also, such initialization is alway done when class instances are created, so no ambiguity here. Moreover, such declarations are not mixed with code, so less chance of getting confused. On the other hand, all other variables must be explicitly initialized.

**Comment by Night-walker** [comment]
I see. Then what's left is to forbid non-class variables defined without a value.

**Comment by daokoder** [comment]
Done.

**Comment by Night-walker** [comment]
Then the issue is resolved.
