### ISSUE TITLE
Inconsistent typing on tuples

### ISSUE THREAD

**Issue by dumblob** [daokoder/dao#402]
Constant can be used to access n-th item, but variable not:
~~~~
0$ dao -e 'x=("s0", 1, 2, 3); i=2; x[i]+=10; io.writeln(x)'
[[ERROR]] in file "command line codes":
  At line 0 : Invalid function definition --- " __main__() ";
  At line 1 : Invalid virtual machine instruction --- " ADD:8,9,8 ";
In code snippet:
      9 :  DATA_I      :     2 ,    10 ,     9 ;     1;   10
>>   10 :  ADD         :     8 ,     9 ,     8 ;     1;   x[i]+=10
     11 :  SETI        :     8 ,     7 ,     5 ;     1;   x[i]
  At line 1 : Invalid operation on the type --- " x[i]+=10 ";
  At line 1 : Inconsistent typing --- " 'string|int' with 'int' ";
1$ dao -e 'x=("s0", 1, 2, 3); i=2; x[2]+=10; io.writeln(x)'
( "s0", 1, 12, 3 )
= none
0$
~~~~

**Comment by dumblob** [comment]
Also, there are tests for this case in `tests/test_tuples.dao`, but without using constants.

**Comment by Night-walker** [comment]
Taking into account static typing, it's obviously not possible to properly resolve indexed item's type without using constant index. Thus I don't think there is much gain to allow variable indexing, with the only exception being `tuple<...: T>` types.

**Comment by dumblob** [comment]
Sure, but this significantly reduces the general usefulness of indexing in tuples. Actually, it boils down to a "different syntax" for few separate variables instead of one variable with static indexing.

This is very painful e.g. in cycles (`t=("a", 5); for(i=0:%t){ switch(i){ case 0: io.writeln(t[0]); case 1: io.writeln(t[1]) } }` looks really awful), where `for-in` doesn't make sense (which is **very common** for tuples with mixed types).

**Comment by Night-walker** [comment]
I don't understand why do you want to use tuples *with the number of elements known at compile time* as lists. They are essentially structures, not containers. I think the right way would be to cast such a tuple to `tuple<...: T>` and then use variable indexing, making it *explicit* that `T`-typed values are yielded.

**Comment by daokoder** [comment]
When sub-indexing a tuple with a variable index, the result can only be inferred to be a variant type. That's why `x[i]+=10` does not work. I think such use should be discouraged, unless the tuple has type in the form of `tuple<...: T>` or all items has the same type. First, it is not very common to use; second, it makes it easier to write messy code.

Consider your first example, the code is clearly not very readable or reasonable, because you need to assume or make sure the index is in the right range, otherwise, the code would become incorrect. A simple way to improve would be grouping the integer items in a sub-tuple: `x=("s0", (1, 2, 3)); `, then you can use variable indexing on the sub-tuple.

For your second example, you really do not need switch-case, since you have no operation on the tuple items. If you do need, you might want to use `(a, b)=t`, and then do whatever with `a` and `b`.

**Comment by dumblob** [comment]
>I don't understand why do you want to use tuples with the number of elements known at compile time as lists.

Because of semantics (and also performance - compare e.g. tuple trees and list trees).

>I think the right way would be to cast such a tuple to tuple<...: T> and then use variable indexing, making it explicit that T-typed values are yielded.

Casting is in this case boilerplate code. Imagine routines/methods with variable number of arguments.

**Comment by dumblob** [comment]
> A simple way to improve would be grouping the integer items in a sub-tuple: x=("s0", (1, 2, 3));, then you can use variable indexing on the sub-tuple.

This sounds reasonable. Still the variable number of arguments of different types need `for-in` with some additional indexing logic around.

**Comment by Night-walker** [comment]
> I think the right way would be to cast such a tuple to tuple<...: T> and then use variable indexing, making it explicit that T-typed values are yielded.
> Casting is in this case boilerplate code. Imagine routines/methods with variable number of arguments.

With such logic, means of static typing in whole are just meaningless, boilerplate code :) The reason why I emphasize the use of explicit casting is code clarity. It's better when variant and dynamic typing is explicitly defined instead of crawling in implicitly, causing daunting errors afterwards.

**Comment by dumblob** [comment]
Well, again - my realy awfully bad reading mistake. From the very beginning, I was reading the `operation` as `fetch operation` instead of `arithmetic operation` and thought, that the issue is in impossibility of doing `my_tuple[int_variable]` and not in performing the `+` arithmetic operation.

**I'm closing this issue as completely invalid.**

Just for reference, I'm putting here my comment I was about to submit, but realized my mistake.

>Sure, I'm not talking about means of static typing in general. I love static typing (and casting).
>
>Still, tuple is more like a structure. And structs are often used e.g. as a container for TLV content (anything serialized or packeted - e.g. from network). It can be nicely demonstrated with the use of variable number of arguments:
>~~~~ruby
# how many values (disregarding their type) were passed to this function?
routine r2(...: tuple<enum<count>, int>|tuple<enum<value>, string|int> as z) {
  x = 0
  y = 0
  while (x < %z) { x += ((tuple)z[x])[1] +1; ++y; }
  return x-y
}
# this actually builds one big tuple in background
r2(
  count = 3,
  value = "a",
  value = 99,
  value = "b",
  count = 2,
  value = "x",
  value = 88,
)
~~~~
>How would you write this efficiently (i.e. e.g. without reading every single piece of the tuple) and without boilerplate code? So the question is, why not simply return `int|string` instead of raising an error?
