### ISSUE TITLE
Unable to execute source files on Windows

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#403]
```ruby
C:\Users\Алексей\Downloads>dao test.dao
WARNING: the path of the executable cannot be located!ERROR: cannot open file "C
:/Users/Алексей/Downloads/test.dao";
```
Loading from the interactive mode works.

**Comment by daokoder** [comment]
This must have something to do with the encodings of the paths. I just made a couple improvement to Dao_OpenFile() and Dao_FileStat(). I wonder if that could fix this problem.

**Comment by Night-walker** [comment]
Yes, it's fixed.
