### ISSUE TITLE
Var/invar handling is broken

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#404]
This
```js
routine test(){
    invar i = 1
    var j = i

    j -= 1
}
```
gives
```
Constant or invariable cannot be modified --- " j -= 1 ";
```

At the same time, this
```js
routine test(){
    invar i = {}
    var j = i

    j.append(1)
}
```
is fine?!

**Comment by dumblob** [comment]
Other (maybe related) (in)var issues:
* https://github.com/daokoder/dao/issues/360
* https://github.com/daokoder/dao/issues/364

**Comment by daokoder** [comment]
Now this issue and issue #360 are fixed.

**Comment by Night-walker** [comment]
Excellent, everything seems fine.
