### ISSUE TITLE
object ?< interface

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#411]
```ruby
class A {}
interface I {}

a = A()
a ?< A # true

switch (a) type {
case I: ... # matched
}

a ?< I # types not matching
```
The last line should work too.

**Comment by daokoder** [comment]
Operator `?<` only checks for same types and **derived** types. So the last line should not work.

**Comment by Night-walker** [comment]
OK, it actually makes sense. Nothing to be done here, closing.
