### ISSUE TITLE
Stream refcount issue

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#425]
```ruby
(dao) load xml
= none
(dao) w = xml::Writer() # creates new stream with DaoStream_New()
= Writer[0x657f00]
(dao) q # the destructor calls DaoGC_DecRC()
 refCount not zero 0x60faa0 23: 1
type: Stream 13 0x60faa0	        0x60faa0 23 1 0
```

**Comment by daokoder** [comment]
The bug is in the `xml` module, due to one missing reference increment. Now fixed and committed.

BTW, how about exposing some C API in `dao_xml.h`, so that it can be used as a C library too. It is useful when other modules in C may need to parse XML files.

**Comment by Night-walker** [comment]
> BTW, how about exposing some C API in dao_xml.h, so that it can be used as a C library too. It is useful when other modules in C may need to parse XML files.

That would require certain code reorganization...

**Comment by daokoder** [comment]
No need in hurry. I can do that when I really need:)
