### ISSUE TITLE
Bug: arithmetic operators' priorities

### ISSUE THREAD

**Issue by dumblob** [daokoder/dao#431]
This looks quite serious. The worst thing is, that I was unable to come up with proper parenthesizing of the expression to get the same weird result.
~~~~ruby
0$ dao -e 'p=2700; io.writeln(5.0/30.0 * p + 11.0/31.0 * p)'
0.521505
= none
0$ dao -e 'p=2700; io.writeln( ((5.0/30.0) * p) + ((11.0/31.0) * p) )'
1408.064516
= none
~~~~

**Comment by daokoder** [comment]
That seems to be a constant folding bug. If you replace `30.0` with a variable, the result will be correct.

**Comment by daokoder** [comment]
Fixed.
