### ISSUE TITLE
invar and initialization of array<> - types not matching

### ISSUE THREAD

**Issue by dumblob** [daokoder/dao#436]
~~~~ruby
invar someval = (0, 0.3, 7)
it = -1
invar data = array<float>( %someval ){ someval[++it] }
~~~~
~~~~
[[ERROR]] in file "/home/test/invar_array_issue.dao":
  At line 0 : Invalid function definition --- " __main__() ";
  At line 3 : Invalid virtual machine instruction --- " RETURN:14,1,70 ";
In code snippet:
     19 :  GETI_TI     :    11 ,    12 ,    14 ;     3;   someval[++it]
>>   20 :  RETURN      :    14 ,     1 ,    70 ;     3;   [++it]
     21 :  GOTO        :     0 ,    12 ,    70 ;     3;   }
  At line 3 : Types not matching --- " [++it] ";
~~~~
with `list` it works:
~~~~ruby
invar someval = {0, 0.3, 7}
it = -1
invar data = array<float>( %someval ){ someval[++it] }
~~~~
with only int `fields` in the tuple it works:
~~~~ruby
invar someval = (0, 3, 7)
it = -1
invar data = array<float>( %someval ){ someval[++it] }
~~~~
and with only `float` fields in the tuple it works as well:
~~~~ruby
invar someval = (0.0, 0.3, 0.7)
it = -1
invar data = array<float>( %someval ){ someval[++it] }
~~~~

**Comment by Night-walker** [comment]
It's quite tricky, actually. With a generic tuple, it's impossible to deduce what value type will be yielded on indexing with non-constant `it`. Thus it is not clear what type the resulting array is supposed to have. I wouldn't expect this to work, albeit the error message could be improved.

**Comment by dumblob** [comment]
That's not an issue - it works for `list`, but especially for non-`invar` tuples (I forgot to put it to the initial post):
~~~~ruby
someval = (0, 0.3, 7)  # now it's not invar and it works
it = -1
invar data = array<float>( %someval ){ someval[++it] }
~~~~

**Comment by Night-walker** [comment]
I missed the explicit array type. And if it actually works for `var`-tuples, it indeed should do so for `invar` as well.

**Comment by daokoder** [comment]
Fixed. The problem was that `invar<int|float>` was not handled properly.

**Comment by dumblob** [comment]
Thanks, it works now.
