### ISSUE TITLE
An alias for timestamps

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#437]
I think we need a built-in `int` alias for `time_t` values to use it in standard libraries. Something like `std::Timestamp`.

**Comment by daokoder** [comment]
Please elaborate why it should be a built-in alias.

**Comment by Night-walker** [comment]
Because returning `int` is not self-describing and creating a separate alias in each concerned module would be ridiculous.

**Comment by daokoder** [comment]
Isn't the time module an ideal place to define such type?

**Comment by Night-walker** [comment]
Well, how would I use it in `os.fs` or `net.http`? Requiring `time` to be loaded as well wouldn't be nice, I guess.

**Comment by daokoder** [comment]
> Requiring `time` to be loaded as well wouldn't be nice

Requiring is acceptable, I think. Though I feel that the problem for this is Windows again.

**Comment by Night-walker** [comment]
I'm not sure it's a good idea to force users to load another shared library regardless of whether they do or do not intend to work with datetimes. But perhaps it's a trifle.

**Comment by daokoder** [comment]
> I'm not sure it's a good idea to force users to load another shared library regardless of whether they do or do not intend to work with datetimes. 

If the timestamp is intended to be `time_t`-like, it is not necessary to work with `time` to use this type. But I prefer the timestamp to support fraction seconds (it can be the number of microseconds since 2000-1-1, like in PostgreSQL, since the Julian Epoch), so one might have to use `time` for this. And in this case, this timestamp should use 64 bit int.

**Comment by dumblob** [comment]
>But I prefer the timestamp to support fraction seconds (it can be the number of microseconds since 2000-1-1, like in PostgreSQL, since the Julian Epoch), so one might have to use `time` for this.

Sound like a good idea.

**Comment by Night-walker** [comment]
`time` does not support less-then-seconds anyway.

**Comment by daokoder** [comment]
> `time` does not support less-then-seconds anyway.

It should. I already have something in the `SQL` module for this, I can adapt that to `time`.

**Comment by dumblob** [comment]
I think @Night-walker meant `time()` from `<time.h>`, but I understood, that @daokoder meant the `time` module.

**Comment by Night-walker** [comment]
I meant the `time` module. Anyway, if microseconds are to be included into the timestamp, even 64-bit integer won't be sufficient. `time_t` should normally be 8-byte on its own.

**Comment by dumblob** [comment]
Of course, if we want fractions (not microseconds, but nanoseconds), then we need full-featured `struct timespec` - I think this is what @daokoder meant.

**Comment by daokoder** [comment]
> I meant the time module. Anyway, if microseconds are to be included into the timestamp, even 64-bit integer won't be sufficient.

Well, it is indeed insufficient for representing time of dozens of thousand years earlier or later. But for a foreseeable and unforeseeable:) future, it is sufficient.

> time_t should normally be 8-byte on its own.

Not always.

> Of course, if we want fractions (not microseconds, but nanoseconds), then we need full-featured struct timespec - I think this is what @daokoder meant.

In `SQL`  I used tuple. If we use an alias of `int`, 64 bits is the maximum we can get.

**Comment by Night-walker** [comment]
> Well, it is indeed insufficient for representing time of dozens of thousand years earlier or later. But for a foreseeable and unforeseeable:) future, it is sufficient.

What dozens of thousands? Years beyond 2038 already cannot be represented by 32-bit value.

**Comment by daokoder** [comment]
> What dozens of thousands? Years beyond 2038 already cannot be represented by 32-bit value.

I was talking about using 64 bit int for timestamp with microsecond precision.

**Comment by dumblob** [comment]
I'm opposed to introducing a separate time type not supporting nanoseconds. We should use plain `int` for that.

Also, I don't see it as an issue, if the new time type has two fields - seconds (internally `time_t` - varying size on different systems - POSIX requires it being an "arithmetic type" which is integer type I suppose) and nanoseconds (internally `long` - at least 32b integer) according to POSIX.

And yes, 2038 (or few tenths of years more) is definitely not enough :(

**Comment by Night-walker** [comment]
> I was talking about using 64 bit int for timestamp with microsecond precision.

Timestamp with microseconds implies 64-bit `time_t` value plus another 32-bit value.

**Comment by daokoder** [comment]
> Timestamp with microseconds implies 64-bit time_t value plus another 32-bit value.

You can encode that into a single 64 bit int with a smaller range. That's how is done in PostgreSQL for the TIMESTAMP type.

**Comment by Night-walker** [comment]
> You can encode that into a single 64 bit int with a smaller range. That's how is done in PostgreSQL for the TIMESTAMP type.

RIght, that's an option.

**Comment by dumblob** [comment]
`microseconds` are not enough - imagine the speed of current network devices - already today it's impossible to distinguish time of two small packets in a row using microseconds.

**Comment by Night-walker** [comment]
> microseconds are not enough - imagine the speed of current network devices - already today it's impossible to distinguish time of two small packets in a row using microseconds.

I don't remember seeing nanosecond-precision timestamps anywhere. Everything smaller then a microsecond is likely to be insignificant or impossible to measure properly.

**Comment by daokoder** [comment]
> microseconds are not enough - imagine the speed of current network devices - already today it's impossible to distinguish time of two small packets in a row using microseconds.

Microsecond-resolution timestamp is clearly not intended for that kind of application. But it is sufficient for the most of applications. Also, note that *timestamp* is usually used for logging certain events, one rarely needs to log sub-microsecond events. For higher resolution, we can enhance `DateTime` type for that.

Maybe we can use an alias of `complex` for timestamp. As long as double precision floating point number is used, it can support sufficient range and resolution.

Speaking about `DateTime`, currently it is invariable, but often I do need it to be mutable to avoid creating many temporary `DateTime` objects. For instance, I need to check time semi-regularly with small intervals, any idea how to do this without creating new `DateTime` objects?

**Comment by Night-walker** [comment]
> Speaking about DateTime, currently it is invariable, but often I do need it to be mutable to avoid creating many temporary DateTime objects. For instance, I need to check time semi-regularly with small intervals, any idea how to do this without creating new DateTime objects?

That would imply creating a lot of additional functions which reuse existing `DateTime` instead of creating a new one, which would look bloated and nonsensical. For cases like comparing timestamps, timeouts, etc. using plain `time.value()` should suffice.

**Comment by dumblob** [comment]
>Maybe we can use an alias of complex for timestamp. As long as double precision floating point number is used, it can support sufficient range and resolution.

I've been thinking about this as well, but wasn't sure (I've never measured the precision difference between `long long` and IEEE 754 `double`, but it really might be sufficient).

**Comment by Night-walker** [comment]
After all, I think the simplest and most natural thing to do is using actual `DateTime` directly in all modules which expose date&time info. Dependencies between modules are inevitable anyway.

**Comment by Night-walker** [comment]
Done.
