### ISSUE TITLE
daomake does not create makefile for net.http

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#440]
`net/http/makefile.dao` follows the same steps as `os/fs/makefile.dao`, but the latter works and the former doesn't. No `Makefile` is created and no error is reported.

**Comment by daokoder** [comment]
Currently DaoMake is unable to handle project name clashing, you may need to change `DaoHttp` in the `makefile.dao` to something else for now.

**Comment by Night-walker** [comment]
OK, resolved.
