### ISSUE TITLE
DaoVmSpace_LinkModule() does not work properly on Windows

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#441]
When I try `load net.http`, I get error saying that `dao_time.dll` cannot be located. That does not happen if I first write `load time`.

**Comment by daokoder** [comment]
Currently DaoMake is unable to handle project name clashing, you may need to change `DaoHttp` in the `makefile.dao` to something else for now.

**Comment by daokoder** [comment]
Fixed, as described in https://github.com/daokoder/dao-modules/issues/65.
