### ISSUE TITLE
Alternative syntax for constants

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#447]
Using capitalized names for constants, i.e. `NAME`, is *de facto* the standard naming convention for them. Dao also adheres to it.

So, why not remove the `const` keyword in favor of distinguishing the constants by names only, as in Ruby or Scala? Simplifies the syntax, unifies the notation. I see two options here:
```ruby
invar NAME = value
static NAME = value
```

Not that I'm a fan of this naming convention, but it is the preferred choice regardless.

**Comment by dumblob** [comment]
I don't have any specific opinion on this, but I'm not against.

**Comment by daokoder** [comment]
> So, why not remove the const keyword in favor of distinguishing the constants by names only, as in Ruby or Scala? 

This sounds like a bit hacking.

> Simplifies the syntax, unifies the notation

Are you saying the current `const` syntax is too complicated? :)

I think someone has proposed this before, but it was rejected. I am afraid I will not change my mind this time.

**Comment by Night-walker** [comment]
I'm just seeking ways to simplify the language. I am also used to `const`, but it isn't the only possible way. Anyway, if it's not to your taste, the discussion is closed.
