### ISSUE TITLE
Incorrect path searching on module loading

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#457]
For some reason, current directory takes precedence over standard modules library when loading stuff. That means one can create fake standard modules, placing the files with identical names in the current directory.

**Comment by dumblob** [comment]
Awesome, my downstream list of Dao issues has already half a year on the top an item "dangerous to use pwd for library loading", so I definitely agree with removing. Once Dao will be getting incorporated into distributions or anywhere on production systems, this will be one of the first patches needed because of security concerns (this was btw one of the biggest issues with DOS :)).

**Comment by daokoder** [comment]
The problem is that the Dao VM does not distinguish between standard and non-standard modules, not even between user scripts and modules. The only way to fix this is to let the vm know which are (standard) modules. We may need to create a manifest file for modules for this.

**Comment by Night-walker** [comment]
No need to make things complex. The VM should just first consult the `lib` directory, and only then the current one.

**Comment by dumblob** [comment]
>No need to make things complex. The VM should just first consult the lib directory, and only then the current one.

It shouldn't consult the current directory at all due to security reasons. It's also very easy to name the module the same - detection of this would be overkill, so it's another reason for disabling such functionality). It should be though possible to tell dao where and in which order to search for libs. On UNIX, the proper way is to use environment variables, but on Windows, this is not user friendly, so I'd rather choose some other way than environment variables. Maybe a command line argument?

**Comment by Night-walker** [comment]
> It shouldn't consult the current directory at all due to security reasons.

And how then it should load local files?

**Comment by dumblob** [comment]
I wasn't clear. There shouldn't be any "current directory" path in the Dao binary nor in any Dao binary modules and also the `load` statement in Dao scripts (be it main files or modules) should not search through the current directory (especially if the `load` statement is in a system-wide module).

There seems to be no path issue with binary libraries (except for  https://github.com/daokoder/dao/issues/406) any more. The only remaining issue is thus the `load` statement looking for modules **by default** in the current directory.

Also now I noticed that there is no need for a new option - Dao already supports that:
~~~~
dao -h
...
   --path=directory      add module searching path;
...
~~~~
So it boils down just to a removal of the current directory from the `load` statement.

**Comment by Night-walker** [comment]
> So it boils down just to a removal of the current directory from the load statement.

Then Dao scripts won't be able to load other files from the current directory.

**Comment by dumblob** [comment]
Why not? `dao --path=. my_script_with_many_local_loads_of_other_scripts_containing_again_many_other_local_and_non-local_loads.dao` should make the job and it's safe.

**Comment by Night-walker** [comment]
It would be extremely wild and impractical to require `dao --path=. ` just to run scripts. No language ever made this so non-trivial.

**Comment by dumblob** [comment]
Well, other languages (at least those which mean security seriously) do it the other way round - they put burden on the programmer to write either full paths in load-like statements or use some different syntax (e.g. some prefixes) for local stuff than for global/system-wide stuff.

**Comment by Night-walker** [comment]
> Well, other languages (at least those which mean security seriously) do it the other way round - they put burden on the programmer to write either full paths in load-like statements or use some different syntax (e.g. some prefixes) for local stuff than for global/system-wide stuff.

Never seen anything like this. And I don't think security like this has any real meaning for a scripting language.

**Comment by dumblob** [comment]
> Never seen anything like this. And I don't think security like this has any real meaning for a scripting language.

Well, then we have to check all paths for the same module name and report conflicts. Otherwise we will silently shadow all other modules with the same name. On Windows this'll get very easy - somebody will download a single executable deployed application to some directory where there is also some Dao script with a common name (`time` or `zip` or whatever) and this script is moving files around or removing them or doing some other potentially harmfull stuff.

Well, and then this poor guy just double clicks the executable (containing the single executable deployed Dao application) and he's scrued, because nobody would think, that such application would look around for some modules and even if it did, than definitely not running them.

**Comment by Night-walker** [comment]
> Well, then we have to check all paths for the same module name and report conflicts. Otherwise we will silently shadow all other modules with the same name.

It's the user's problem if he/she named a module like a standard one. It can hardly go unnoticed, so I wouldn't pay attention to this issue at all.

**Comment by dumblob** [comment]
I was talking about user application - a bundled one, so you don't see what's inside. You know Windows users (even if they're programmers) - just click -> click -> click -> done.

**Comment by daokoder** [comment]
I just made one minor change that will set the working directory to the directory of the main script in `DaoVmSpace_RunMain()`. This should avoid the problem mentioned above.

However, before `DaoVmSpace_RunMain()`, the working directory is still the directory where the Dao command is started. So if one wants to load modules with command line options before starting the main script, one should use full paths.

**Comment by Night-walker** [comment]
OK, but script's directory should still be searched only after `lib`.

**Comment by daokoder** [comment]
> OK, but script's directory should still be searched only after lib.

Not necessarily, the main script is likely to load a local script of the same or similar location first. Search lib first could lead to problems.

**Comment by Night-walker** [comment]
Preferring local script to a standard module may be confusing if users abuse this behavior aspect.

**Comment by daokoder** [comment]
> Preferring local script to a standard module may be confusing if users abuse this behavior aspect.

You mean naming a local script with the same name as a standard module, or something like this? If the naming is intentional, it is not our problem. If it is accidental, we might need to do something. In both cases, something like a module manifest should solve the issue.

**Comment by dumblob** [comment]
Yes, module manifest should solve it and I'm likely to support this idea, but there is one thing - it's the manifest dynamic updating (e.g. adding user modules into system-wide standard library). Do you have any portable (so we can't rely on file system features like symbolic links etc.) and very simple idea?

**Comment by Night-walker** [comment]
I like it when module is a file. Single entity. Words like 'manifest' bring up thoughts of Windows, Java and so on. After all, I don't think this is such a problem, given that at least Python's behavior is no different.

**Comment by dumblob** [comment]
Python wasn't designed for single file deployment and there are still huge issues with that (on UNIX it kind of works, but on Windows it's more difficult). So I think Python is not a good nor valid example.

On the other hand I agree, that manifest brings usually more issues than it solves, but I'm really afraid of the case I described above. If there will be some easy way to prevent it, then I won't vote for manifest.

**Comment by Night-walker** [comment]
I am against any kind of manifests. If it is so necessary (of which I am not sure), distinction can be made with `load` itself. For instance, it is possible to oblige to use quoted names for local files and unquoted -- for standard modules.

**Comment by daokoder** [comment]
> For instance, it is possible to oblige to use quoted names for local files and unquoted -- for standard modules.

I have also considered this possibility. Another alternative I have considered is to scan the module directory and automatically create a "manifest" for the module files. The later is obviously more complicated and has a high startup overhead. But the former isn't very elegant. I prefer not to make such change.

Yet another possibility is that, for load statements user scripts, we search in both the working path and the module path, and raise an warning if there is a name conflict.

**Comment by Night-walker** [comment]
> Yet another possibility is that, for load statements in user scripts, we search in both the working path and the module path, and raise a warning if there is a name conflict.

I think that would be sufficient.

**Comment by dumblob** [comment]
>Yet another possibility is that, for load statements in user scripts, we search in both the working path and the module path, and raise a warning if there is a name conflict.

That's what I wrote above ("we have to check all paths for the same module name and report conflicts"), but it might get very slow once there are more modules and more module paths. I think though, that with caching, the only bottleneck remaining will be the cold start, which shouldn't be a big issue nowadays.

**Comment by daokoder** [comment]
Done. The overhead is not a big issue, it doubles `load` time at the worst. Also, `load` is an infrequent operation.
