### ISSUE TITLE
io.writef() sometimes prints memory garbage

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#460]
It cannot be 100% reproduced, but playing with formats and arguments eventually brings this issue up. For instance:
```ruby
(dao) io.writef('%s')
skipped= none
```
Sometimes it complains about wrong N-th parameter when no such parameter was passed, likely accessing the memory it is not supposed to.

**Comment by daokoder** [comment]
I cannot reproduce the error, but I did find and fixed a minor bug in the code, it seems that fix should fix this issue.

**Comment by Night-walker** [comment]
Seems fixed.
