### ISSUE TITLE
Wrapped function params may become corrupted?

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#461]
The last commit to `test` fixes SIGSEGV which I caught on accessing `p[0]` in `TEST_AssertError` after issuing `DaoProcess_Execute()`. Happened on `time/tests.dao`. Not sure if it is the intended behavior.

**Comment by daokoder** [comment]
`p` might be a part of the vm stack, executing `DaoProcess_Execute()` may cause it to be reallocated, so you should not access it after `DaoProcess_Execute()`. Your fix is the right way to handle it.

**Comment by Night-walker** [comment]
OK, question solved.
