### ISSUE TITLE
Print floats with full precision by default

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#465]
Printing only 6 fractional digits is not enough; it may be misleading when comparing numbers.

**Comment by dumblob** [comment]
According to the table with approximate decimal precision for [interchangeability of floating point numbers](https://en.wikipedia.org/wiki/IEEE_floating_point#Basic_and_interchange_formats) the length for double precision (our case) is 53 digits. Do you really want to print about 53 (fractional) digits every time? Or what do you mean by "full precision"?

**Comment by Night-walker** [comment]
> Or what do you mean by "full precision"?

The one printed by `printf()` with `%f`.

**Comment by Night-walker** [comment]
Actually, `printf()` prints 6 fractional digits with `%f`... Then I suppose it is better to live things unchanged.
