### ISSUE TITLE
A daunting behavior of DaoProcess_PutTuple()

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#471]
It was very surprising for me to discover that `DaoProcess_PutTuple()` may return garbage. If not the comment in `os.fs`, I'd never thought that it's not a bug. It is highly desirable to make the function automatically clear the string fields in the returned tuple, as well as any other affected containers.

And if there are other cases when garbage may be returned (`DaoProcess_NewTuple()`?), please let me know. I can't possibly guarantee correctness of my code with surprises like this one.

**Comment by daokoder** [comment]
> It was very surprising for me to discover that DaoProcess_PutTuple() may return garbage. If not the comment in os.fs, I'd never thought that it's not a bug. It is highly desirable to make the function automatically clear the string fields in the returned tuple, as well as any other affected containers.
>
And if there are other cases when garbage may be returned (DaoProcess_NewTuple()?), please let me know. I can't possibly guarantee correctness of my code with surprises like this one.

Please don't overreact, it was intended as an optimization. I agree that it was a dangerous one, so I removed it now.

**Comment by Night-walker** [comment]
It's just that there was virtually no way to know about that kind of behavior in advance. Anyway, fixed. Don't mind the drama -- I didn't meant to offend or anything, just a bit stir-up :)
