### ISSUE TITLE
SIGSEGV with array::resize()

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#494]
```ruby
(dao) a = [1]
= [ 1 ]
(dao) a.resize([])
Segmentation fault (core dumped)
```

**Comment by daokoder** [comment]
Fixed.

**Comment by Night-walker** [comment]
Now I cannot resize array to 0 elements.

**Comment by daokoder** [comment]
Try `a.resize([0, 0])`. But it should be improved somehow, I am considering to support `resize( size: int )` for vectors.

**Comment by Night-walker** [comment]
It's definitely not intuitive to use `[a, b]` to resize single-dimensional array. Maybe it's better to switch to `resize(...: int)`.

**Comment by dumblob** [comment]
>It's definitely not intuitive to use `[a, b]` to resize single-dimensional array. Maybe it's better to switch to `resize(...: int)`.

I have the same feeling.

**Comment by daokoder** [comment]
> Maybe it's better to switch to resize(...: int)

Good idea, it will be done:)

**Comment by daokoder** [comment]
Done.
