### ISSUE TITLE
Question: how to open and create files in Dao

### ISSUE THREAD

**Issue by dumblob** [daokoder/dao#510]
One of the latest changes was removal of the `io::open()` methods (as suggested by @Night-walker in some issue I can't find right now). But these were not added anywhere else.

What's the preferred way to open, create and read/write files right now? There is a `Device` type and `Stream` type - both more or less suitable for some work with files, but there is no way to create them as wrappers for regular files. Regarding creation, I mentioned it, because I don't want to call `Dir::newFile()` each time I'm creating a new file.

**Comment by Night-walker** [comment]
The stuff was moved to `stream` module.

**Comment by dumblob** [comment]
Thanks! I was searching through the *dao-modules* repository and missed the fact, it's in the *dao* repository.
