### ISSUE TITLE
Bug: built-in regex engine treats space in a pattern in a special way

### ISSUE THREAD

**Issue by dumblob** [daokoder/dao#514]
~~~~
0$ dao -e 'if (" řč óě ".match("řč óě") != none) io.writeln("howk")'
= none
0$ dao -e 'if (" řčóě ".match("řčóě") != none) io.writeln("howk")'
howk
= none
~~~~

**Comment by Night-walker** [comment]
Surely it does. All whitespace outside of `[]` in patterns is ignored, which is a nice feature because it allows to write human readable regexes.

**Comment by dumblob** [comment]
>which is a nice feature because it allows to write human readable regexes.

About 50% of my extensive regexes use substrings from sentences written by humans. Sentences contain spaces (and tabs and other white-space characters as well). As do the substrings, so it's actually quite inconvenient to first prefix all whitespace characters with `%`.

In general I noticed, that regexes I use in Dao strongly tend to be more verbose and less readable then [ERE](http://pubs.opengroup.org/onlinepubs/009696899/basedefs/xbd_chap09.html#tag_09_04)s or [PCRE](http://www.pcre.org/)s or [RE2](https://github.com/google/re2)s, just because of extensive escaping of common characters - especially white space characters (and using `.change("(%s)", "%%%1")` for each pattern is not the best idea either - besides it's often impossible). I know, that the comparison to other substantially different regex engines is not fair, but I really struggle with the extensive escaping.

**Comment by daokoder** [comment]
> About 50% of my extensive regexes use substrings from sentences written by humans. Sentences contain spaces (and tabs and other white-space characters as well). As do the substrings, so it's actually quite inconvenient to first prefix all whitespace characters with %.

Then you should use `{{substring}}`. You only need to make sure `substring` does not contain `}}`.

**Comment by Night-walker** [comment]
From my experience, even a regex larger then 20 characters is often not easy to read without delimiters. Spacing helps a lot. Anyway, there is `regex` module with customizable rules for grammar preprocessing which should do the job the way you want.

**Comment by dumblob** [comment]
>Then you should use `{{substring}}`. You only need to make sure substring does not contain `}}`.

Thanks, I didn't find this in documentation, but it should be enough for my use cases. Could we add it to the pattern documentation? The customizable grammar in the `regex` module would be overkill for most of my use cases so far.

**Comment by dumblob** [comment]
Documentation fixed in https://github.com/daokoder/dao-modules/commit/b583db56803fcd83acb830f895bcde901c4c8cca .
