### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by bfontaine** [daokoder/dao#536]
Hello,
Two years ago (https://github.com/daokoder/dao/issues/513#issuecomment-147615564) you wrote:

> Now there is a simple and unspoken roadmap: 1. solve all/most the issues here; 2. make a module management tool. In terms of releases, there should be at least 3 releases to go before the next official release: at least 1 beta release and 2 RC releases.

On [HN](https://news.ycombinator.com/item?id=15016704) today, you wrote that “<i>the language is stable now in terms of features, there will be no more significant changes in the language in the forseeable future</i>”.

On GitHub, the last release is tagged [`2.0-beta3`](https://github.com/daokoder/dao/releases/tag/Dao-2.0-Beta3) and was in 2014. Do you plan on releasing a stable version at some point?

Thanks!

**Comment by daokoder** [comment]
Given the current status of Dao and my work plans, I will skip the mentioned beta release, and go with RC releases directly before a stable release. I will try to make a RC release (RC1) within a few weeks. The schedule for second RC release will depend on the feedbacks from RC1, but should be within 3 months after RC1. There could be one more RC release if necessary. The official stable release is likely to come out before the middle of 2018, and within 2018 in any case.

**Comment by bfontaine** [comment]
Thank you for your answer! 😃
