### ISSUE TITLE
Makefile.daomake -- Cannot find "../../../kernel/daoConst.c"

### ISSUE THREAD

**Issue by reposefulGrass** [daokoder/dao#537]
![image](https://user-images.githubusercontent.com/26889880/29340856-de3eaa46-81e6-11e7-8152-b4c8aa4df526.png)

![image](https://user-images.githubusercontent.com/26889880/29340877-07bf2404-81e7-11e7-92f0-c8c8b49e1a51.png)

I am on Windows 10, using mingw32.

**Comment by reposefulGrass** [comment]
I gotta go, but I'll try and find out whats going on.

**Comment by reposefulGrass** [comment]
I couldn't find out why its not working, but it works on my ubuntu linux laptop.

**Comment by daokoder** [comment]
It seems all files under *kernel* are not listed. Could it be that *kernel* has special significance in Windows 10 such that it requires root/admin permission to access?

**Comment by reposefulGrass** [comment]
Running as administrator changes nothing. 

I think this is where the error is coming from:  `CreateProcess(NULL, cc -c -O0 -DWIN32 -DMINGW -DDmake (e=2): The system cannot find the file specified.` 

![image](https://user-images.githubusercontent.com/26889880/29380501-8932b0ba-828b-11e7-86bd-5193e1408656.png)

For compiling C programs, I use `gcc`. Don't know what the difference is.

**Comment by reposefulGrass** [comment]
Because its not compiling the daoConst object file, its missing, hence: `The system cannot find the file specified.`

**Comment by reposefulGrass** [comment]
I Guess I don't have G++ installed.

**Comment by reposefulGrass** [comment]
I was wrong, I have g++ installed. Seems there is not `cc` binary anywhere in mingw.

I kinda fixed my original problem wit this variable: `CC == gcc`.

**Comment by reposefulGrass** [comment]
Now I am getting this error, which is basically the same problem, except I cannot just add the `CC = gcc` variable to the makefile in daomaster\.

![image](https://user-images.githubusercontent.com/26889880/29381752-f2757040-828f-11e7-9b39-22857ea5d9a2.png)

**Comment by daokoder** [comment]
Please try *make -f Makefile.daomake mingw CC=gcc*.
